[package]
name = "proc_macro_rc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = {version = "1", features=["full", "extra-traits"]}
proc-macro2 = {version = "1.0"}